name: Build and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.4]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      # - run: npm run test
      - run: npm run build
      - run: rm dist/navbar/index.html
      - run: find dist
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-assets
          path: dist/${{ github.event.repository.name }}
  deploy:
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'mtb-microfrontends-workshop'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: frontend-assets
          path: .
      - id: auth
        uses: google-github-actions/auth@v0.4.1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - id: upload-files
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: .
          destination: mtb.microfrontends.app/apps/${{ github.event.repository.name }}/${{ github.sha }}
          headers: |-
            cache-control: public, max-age=30
      - id: update-import-map
        run: |
          curl -u ${{ secrets.IMD_USERNAME }}:${{ secrets.IMD_PASSWORD }} -d '{"service": "@mtb/${{ github.event.repository.name }}", "url": "https://mtb.microfrontends.app/apps/${{ github.event.repository.name }}/${{ github.sha }}/main.js"}' -X PATCH ${{ secrets.IMD_ORIGIN }}/services?env=mtb -H "Accept: application/json" -H "Content-Type: application/json" --fail